version: "2"
services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        APP_BUILD_ENV: docker-compose-build-arg
    ports:
      - 80:80
    environment:
      - APP_ENV=docker-compose
